const LOG_IN = 'APP/LOG_IN';
const LOG_IN_SUCCESS = 'APP/LOG_IN_SUCCESS';
const LOG_IN_FAILED = 'APP/LOG_IN_FAILED';
const CONNECTION_INFO = 'APP/LOG_IN';

export { LOG_IN, LOG_IN_SUCCESS, LOG_IN_FAILED, CONNECTION_INFO };
